# Generated by Django 5.1.6 on 2025-02-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_alter_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='projects',
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_projects', to='abouts.team')),
            ],
        ),
    ]
