# Generated by Django 4.2.16 on 2025-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0004_remove_team_projects_personalproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='project_link',
            field=models.URLField(blank=True, null=True, verbose_name='Website Link'),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website Link'),
        ),
    ]
