# Generated by Django 5.1.6 on 2025-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0005_personalproject_project_link_team_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('alumni', 'Alumni'), ('expert', 'Expert'), ('founder', 'Founder')], default='member', max_length=10),
        ),
    ]
