# Generated by Django 5.1.6 on 2025-02-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0006_personalproject_link_project_link_team_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalproject',
            name='link',
        ),
    ]
