# Generated by Django 5.1.6 on 2025-03-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0008_team_address_team_email_team_facebook_team_github_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educational Background', 'verbose_name_plural': 'Educational Backgrounds'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.AlterModelOptions(
            name='personalproject',
            options={'verbose_name': 'Personal Project', 'verbose_name_plural': 'Personal Projects'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team Profile', 'verbose_name_plural': 'Team Profiles'},
        ),
    ]
