# Generated by Django 5.1.6 on 2025-03-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0009_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
