# Generated by Django 5.1.6 on 2025-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0010_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('alumni', 'Alumni'), ('external-expert', 'External Expert'), ('co-founder', 'Co-Founder'), ('founder', 'Founder')], default='member', max_length=50),
        ),
    ]
