# Generated by Django 5.1.6 on 2025-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0011_alter_team_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='project_link',
            field=models.URLField(blank=True, max_length=191, null=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='project_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='role',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, max_length=191, null=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, max_length=191, null=True),
        ),
    ]
