# Generated by Django 5.1.7 on 2025-04-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0012_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='role',
            field=models.CharField(help_text='Comma-separated roles', max_length=191),
        ),
    ]
