# Generated by Django 5.1.7 on 2025-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0013_alter_education_options_alter_projectdeveloper_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full role name (e.g., Project Manager)', max_length=191, unique=True)),
                ('acronym', models.CharField(help_text='Short code (e.g., PM)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the role')),
                ('category', models.CharField(choices=[('Core IT', 'Core IT Development Team'), ('Support', 'Support & Auxiliary Roles'), ('Specialized', 'Specialized Roles')], default='Core IT', max_length=20)),
            ],
        ),
    ]
