# Generated by Django 5.1.7 on 2025-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0014_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('pre-deployment', 'Pre-deployment'), ('implemented & maintained', 'Implemented & Maintained'), ('under-maintenance', 'Under Maintenance')], default='implemented & maintained', max_length=50),
        ),
    ]
